entryPoints:
  http:
    address: :80
  https:
    address: :443

providers:
  docker:
    exposedByDefault: false
    endpoint: unix:///var/run/docker.sock
    network: webproxy

api:
  dashboard: true
  insecure: true
